# This workflow will build and test the go-cache Go library package.

name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Verify dependencies
      run: go mod verify

    - name: Build packages
      run: go build -v ./...

    - name: Run unit tests with race detection
      run: go test -v -race ./...

    - name: Run benchmarks
      run: go test -bench . -benchmem ./...
